apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeon-nginx-deployment
  labels:
    app: codeon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codeon
  template:
    metadata:
      labels:
        app: codeon
    spec:
      containers:
      - name: codeon
        image: gautamabhis/codeon1:{{ .Values.image.tag }}
        ports:
        - containerPort: 5173
