apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeon-nginx-ingress
  labels:
    app: codeon
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: codeon.example.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codeon-nginx-service
            port:
              number: 80